# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
loader_version=0.18.4
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version = 3.0.24
maven_group = ca.rttv
archives_base_name = chatcalc
